/* =============================================================================
   Cafeteria Management System (Oracle 19c)
   File: 01_ddl.sql
   Notes:
     - IMPORTANT: run as a SCRIPT (SQL Developer: F5), not statement-by-statement,
       because the cleanup uses PL/SQL blocks terminated with '/'.
     - "ORDER" is a quoted table name and must be referenced as "ORDER".
   ============================================================================ */

/* -----------------------------------------------------------------------------
   OPTIONAL CLEANUP (safe drops)
   --------------------------------------------------------------------------- */
BEGIN EXECUTE IMMEDIATE 'DROP VIEW LowInventory'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW PopularItems'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DailyRevenue'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TYPE OrderSummaryType FORCE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHIFT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAYMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FEEDBACK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INGREDIENT_USAGE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INVENTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "ORDER" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DISCOUNT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MENU_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MENU_CATEGORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUSTOMER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYEE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MENU_CATEGORY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MENU_ITEM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDER_ITEM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INVENTORY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INGREDIENT_USAGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FEEDBACK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAYMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISCOUNT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SHIFT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

/* -----------------------------------------------------------------------------
   TABLE: CUSTOMER
   --------------------------------------------------------------------------- */
CREATE TABLE CUSTOMER (
  CUSTOMER_ID      NUMBER         NOT NULL,
  NAME             VARCHAR2(100)   NOT NULL,
  EMAIL            VARCHAR2(255)   NOT NULL,
  PHONE            VARCHAR2(20)    NOT NULL,
  CUSTOMER_TYPE    VARCHAR2(20)    NOT NULL,
  REGISTERED_DATE  DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT UQ_CUSTOMER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UQ_CUSTOMER_PHONE UNIQUE (PHONE),
  CONSTRAINT CK_CUSTOMER_TYPE CHECK (CUSTOMER_TYPE IN ('Student','Staff','Guest')),
  -- Oracle REGEXP_LIKE uses POSIX ERE; keep patterns Oracle-compatible.
  CONSTRAINT CK_CUSTOMER_EMAIL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$')),
  CONSTRAINT CK_CUSTOMER_PHONE CHECK (REGEXP_LIKE(PHONE, '^[0-9+ \-]{7,20}$'))
);

/* -----------------------------------------------------------------------------
   TABLE: EMPLOYEE
   - ShiftStart/ShiftEnd represent a default daily shift window; actual shifts
     are recorded in SHIFT table.
   --------------------------------------------------------------------------- */
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID   NUMBER         NOT NULL,
  NAME          VARCHAR2(100)  NOT NULL,
  ROLE          VARCHAR2(20)   NOT NULL,
  SALARY        NUMBER(10,2)   NOT NULL,
  HIRE_DATE     DATE           NOT NULL,
  SHIFT_START   VARCHAR2(5)    NOT NULL,
  SHIFT_END     VARCHAR2(5)    NOT NULL,
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
  CONSTRAINT CK_EMPLOYEE_ROLE CHECK (ROLE IN ('Cashier','Chef','Manager')),
  CONSTRAINT CK_EMPLOYEE_SALARY CHECK (SALARY >= 0),
  CONSTRAINT CK_EMPLOYEE_SHIFTSTART CHECK (REGEXP_LIKE(SHIFT_START, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT CK_EMPLOYEE_SHIFTEND CHECK (REGEXP_LIKE(SHIFT_END, '^([01][0-9]|2[0-3]):[0-5][0-9]$'))
);

/* -----------------------------------------------------------------------------
   TABLE: MENU_CATEGORY
   --------------------------------------------------------------------------- */
CREATE TABLE MENU_CATEGORY (
  CATEGORY_ID    NUMBER         NOT NULL,
  CATEGORY_NAME  VARCHAR2(30)   NOT NULL,
  DESCRIPTION    VARCHAR2(400),
  CONSTRAINT PK_MENU_CATEGORY PRIMARY KEY (CATEGORY_ID),
  CONSTRAINT UQ_MENU_CATEGORY_NAME UNIQUE (CATEGORY_NAME),
  CONSTRAINT CK_MENU_CATEGORY_NAME CHECK (CATEGORY_NAME IN ('Main','Beverage','Snack','Dessert'))
);

/* -----------------------------------------------------------------------------
   TABLE: MENU_ITEM
   - AverageRating is denormalized and maintained via trigger after FEEDBACK.
   --------------------------------------------------------------------------- */
CREATE TABLE MENU_ITEM (
  ITEM_ID         NUMBER         NOT NULL,
  CATEGORY_ID     NUMBER         NOT NULL,
  NAME            VARCHAR2(120)  NOT NULL,
  PRICE           NUMBER(8,2)    NOT NULL,
  CALORIE_COUNT   NUMBER(6)      NOT NULL,
  IS_AVAILABLE    CHAR(1)        DEFAULT 'Y' NOT NULL,
  AVERAGE_RATING  NUMBER(3,2)    DEFAULT 0   NOT NULL,
  CONSTRAINT PK_MENU_ITEM PRIMARY KEY (ITEM_ID),
  CONSTRAINT FK_MENU_ITEM_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MENU_CATEGORY(CATEGORY_ID),
  CONSTRAINT UQ_MENU_ITEM_NAME UNIQUE (NAME),
  CONSTRAINT CK_MENU_ITEM_PRICE CHECK (PRICE >= 0),
  CONSTRAINT CK_MENU_ITEM_CAL CHECK (CALORIE_COUNT >= 0),
  CONSTRAINT CK_MENU_ITEM_AVAIL CHECK (IS_AVAILABLE IN ('Y','N')),
  CONSTRAINT CK_MENU_ITEM_AVGR CHECK (AVERAGE_RATING BETWEEN 0 AND 5)
);

/* -----------------------------------------------------------------------------
   TABLE: DISCOUNT
   - Applied by CUSTOMER_TYPE and date validity window.
   --------------------------------------------------------------------------- */
CREATE TABLE DISCOUNT (
  DISCOUNT_ID       NUMBER        NOT NULL,
  CUSTOMER_TYPE     VARCHAR2(20)  NOT NULL,
  DISCOUNT_PERCENT  NUMBER(5,2)   NOT NULL,
  VALID_FROM        DATE          NOT NULL,
  VALID_TO          DATE          NOT NULL,
  CONSTRAINT PK_DISCOUNT PRIMARY KEY (DISCOUNT_ID),
  CONSTRAINT CK_DISCOUNT_TYPE CHECK (CUSTOMER_TYPE IN ('Student','Staff','Guest')),
  CONSTRAINT CK_DISCOUNT_PERCENT CHECK (DISCOUNT_PERCENT BETWEEN 0 AND 80),
  CONSTRAINT CK_DISCOUNT_DATES CHECK (VALID_TO >= VALID_FROM)
);

/* -----------------------------------------------------------------------------
   TABLE: "ORDER"
   --------------------------------------------------------------------------- */
CREATE TABLE "ORDER" (
  ORDER_ID         NUMBER        NOT NULL,
  CUSTOMER_ID      NUMBER        NOT NULL,
  EMPLOYEE_ID      NUMBER,
  ORDER_DATE       DATE          DEFAULT TRUNC(SYSDATE) NOT NULL,
  ORDER_TIME       VARCHAR2(5)   DEFAULT TO_CHAR(SYSDATE,'HH24:MI') NOT NULL,
  TOTAL_AMOUNT     NUMBER(10,2)  DEFAULT 0 NOT NULL,
  STATUS           VARCHAR2(20)  DEFAULT 'Pending' NOT NULL,
  PAYMENT_METHOD   VARCHAR2(10),
  CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  CONSTRAINT CK_ORDER_TIME CHECK (REGEXP_LIKE(ORDER_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT CK_ORDER_TOTAL CHECK (TOTAL_AMOUNT >= 0),
  CONSTRAINT CK_ORDER_STATUS CHECK (STATUS IN ('Pending','Completed','Cancelled')),
  CONSTRAINT CK_ORDER_METHOD CHECK (PAYMENT_METHOD IS NULL OR PAYMENT_METHOD IN ('Cash','Card','Wallet'))
);

/* -----------------------------------------------------------------------------
   TABLE: ORDER_ITEM
   --------------------------------------------------------------------------- */
CREATE TABLE ORDER_ITEM (
  ORDER_ITEM_ID  NUMBER        NOT NULL,
  ORDER_ID       NUMBER        NOT NULL,
  ITEM_ID        NUMBER        NOT NULL,
  QUANTITY       NUMBER        NOT NULL,
  UNIT_PRICE     NUMBER(8,2)   NOT NULL,
  SUBTOTAL       NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES "ORDER"(ORDER_ID),
  CONSTRAINT FK_ORDER_ITEM_MENU FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEM(ITEM_ID),
  CONSTRAINT CK_ORDER_ITEM_QTY CHECK (QUANTITY > 0),
  CONSTRAINT CK_ORDER_ITEM_UNITPRICE CHECK (UNIT_PRICE >= 0),
  CONSTRAINT CK_ORDER_ITEM_SUBTOTAL CHECK (SUBTOTAL = ROUND(QUANTITY * UNIT_PRICE, 2))
);

/* -----------------------------------------------------------------------------
   TABLE: INVENTORY
   - Represents ingredients/raw materials, not menu items.
   --------------------------------------------------------------------------- */
CREATE TABLE INVENTORY (
  INVENTORY_ID       NUMBER         NOT NULL,
  ITEM_NAME          VARCHAR2(120)  NOT NULL,
  UNIT               VARCHAR2(20)   NOT NULL,
  QUANTITY_IN_STOCK  NUMBER(12,3)   DEFAULT 0 NOT NULL,
  REORDER_LEVEL      NUMBER(12,3)   DEFAULT 0 NOT NULL,
  LAST_RESTOCKED     DATE,
  CONSTRAINT PK_INVENTORY PRIMARY KEY (INVENTORY_ID),
  CONSTRAINT UQ_INVENTORY_ITEM UNIQUE (ITEM_NAME),
  CONSTRAINT CK_INVENTORY_QTY CHECK (QUANTITY_IN_STOCK >= 0),
  CONSTRAINT CK_INVENTORY_REORDER CHECK (REORDER_LEVEL >= 0),
  CONSTRAINT CK_INVENTORY_UNIT CHECK (UNIT IN ('kg','g','l','ml','pcs','pack'))
);

/* -----------------------------------------------------------------------------
   TABLE: INGREDIENT_USAGE
   - Bill of materials for each MENU_ITEM: which inventory items are consumed.
   --------------------------------------------------------------------------- */
CREATE TABLE INGREDIENT_USAGE (
  USAGE_ID          NUMBER        NOT NULL,
  ITEM_ID           NUMBER        NOT NULL,
  INVENTORY_ID      NUMBER        NOT NULL,
  QUANTITY_REQUIRED NUMBER(12,3)  NOT NULL,
  CONSTRAINT PK_INGREDIENT_USAGE PRIMARY KEY (USAGE_ID),
  CONSTRAINT FK_USAGE_ITEM FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEM(ITEM_ID),
  CONSTRAINT FK_USAGE_INVENTORY FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID),
  CONSTRAINT UQ_USAGE_ITEM_INV UNIQUE (ITEM_ID, INVENTORY_ID),
  CONSTRAINT CK_USAGE_QTYREQ CHECK (QUANTITY_REQUIRED > 0)
);

/* -----------------------------------------------------------------------------
   TABLE: PAYMENT
   - 1:1 logical with order; enforced via unique ORDER_ID.
   --------------------------------------------------------------------------- */
CREATE TABLE PAYMENT (
  PAYMENT_ID      NUMBER        NOT NULL,
  ORDER_ID        NUMBER        NOT NULL,
  AMOUNT_PAID     NUMBER(10,2)  NOT NULL,
  PAYMENT_DATE    DATE          DEFAULT SYSDATE NOT NULL,
  PAYMENT_STATUS  VARCHAR2(20)  DEFAULT 'Pending' NOT NULL,
  CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID),
  CONSTRAINT UQ_PAYMENT_ORDER UNIQUE (ORDER_ID),
  CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES "ORDER"(ORDER_ID),
  CONSTRAINT CK_PAYMENT_AMOUNT CHECK (AMOUNT_PAID >= 0),
  CONSTRAINT CK_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('Paid','Refunded','Pending'))
);

/* -----------------------------------------------------------------------------
   TABLE: FEEDBACK
   - One feedback per completed order (enforced by unique ORDER_ID).
   --------------------------------------------------------------------------- */
CREATE TABLE FEEDBACK (
  FEEDBACK_ID    NUMBER        NOT NULL,
  CUSTOMER_ID    NUMBER        NOT NULL,
  ORDER_ID       NUMBER        NOT NULL,
  RATING         NUMBER(1)     NOT NULL,
  COMMENTS       VARCHAR2(500),
  FEEDBACK_DATE  DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_FEEDBACK PRIMARY KEY (FEEDBACK_ID),
  CONSTRAINT UQ_FEEDBACK_ORDER UNIQUE (ORDER_ID),
  CONSTRAINT FK_FEEDBACK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  CONSTRAINT FK_FEEDBACK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES "ORDER"(ORDER_ID),
  CONSTRAINT CK_FEEDBACK_RATING CHECK (RATING BETWEEN 1 AND 5)
);

/* -----------------------------------------------------------------------------
   TABLE: SHIFT
   --------------------------------------------------------------------------- */
CREATE TABLE SHIFT (
  SHIFT_ID      NUMBER       NOT NULL,
  EMPLOYEE_ID   NUMBER       NOT NULL,
  SHIFT_DATE    DATE         NOT NULL,
  START_TIME    VARCHAR2(5)  NOT NULL,
  END_TIME      VARCHAR2(5)  NOT NULL,
  HOURS_WORKED  NUMBER(5,2)  NOT NULL,
  CONSTRAINT PK_SHIFT PRIMARY KEY (SHIFT_ID),
  CONSTRAINT FK_SHIFT_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
  CONSTRAINT CK_SHIFT_START CHECK (REGEXP_LIKE(START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT CK_SHIFT_END CHECK (REGEXP_LIKE(END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT CK_SHIFT_HOURS CHECK (HOURS_WORKED BETWEEN 0 AND 24),
  CONSTRAINT UQ_SHIFT_EMP_DATE UNIQUE (EMPLOYEE_ID, SHIFT_DATE)
);

/* -----------------------------------------------------------------------------
   SEQUENCES (all primary keys)
   --------------------------------------------------------------------------- */
CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MENU_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MENU_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVENTORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INGREDIENT_USAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FEEDBACK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DISCOUNT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHIFT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

/* -----------------------------------------------------------------------------
   END
   --------------------------------------------------------------------------- */

